M48
; DRILL file {KiCad (6.0.0-0)} date 2022 March 09, Wednesday 17:47:02
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-03-09T17:47:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
%
G90
G05
T1
X4.245Y-3.094
T2
X5.1359Y-4.2771
X5.6079Y-4.2771
T0
M30
