M48
; DRILL file {KiCad (6.0.0-0)} date 2022 February 02, Wednesday 11:17:39
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-02T11:17:39+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0197
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X5.9904Y-5.1264
T2
X5.551Y-4.733
T0
M30
